[project]
name = "document-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jeremyarancio", email = "jeremyarancio@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pypdfium2>=5.3.0",
    "unsloth>=2026.1.4",
]

[project.scripts]
document-ai = "document_ai:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
